source "https://rubygems.org"

gem "rails", "~> 8.1.1"
gem "puma", ">= 5.0"

# API-specific gems
gem "rack-cors"
gem "jwt"
gem "jbuilder"

gem "bcrypt", "~> 3.1.7"
gem "pagy", "~> 9.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

gem "bootsnap", require: false

gem "kamal", require: false

gem "thruster", require: false

gem "image_processing", "~> 1.2"

# Use PostgreSQL in production (Heroku)
gem "pg", "~> 1.5", group: :production

group :development, :test do
  gem "sqlite3", ">= 2.1"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
